In [1]:
import jittor as jt
import numpy as np
import os
from NeRF_dataset import NeRFDataset

In [2]:
path = 'c:\\Users\\Hypoxanthine\\Desktop\\Jittor\\jittor-nerf-framework\\data\\tiny_nerf_data.npz'

In [3]:
nerfdata = NeRFDataset('npz',path,batch_size=1)

In [5]:
next(nerfdata)

(array([1]),
 jt.Var([[[[0. 0. 0.]
           [0. 0. 0.]
           [0. 0. 0.]
           ...
           [0. 0. 0.]
           [0. 0. 0.]
           [0. 0. 0.]]
        
          [[0. 0. 0.]
           [0. 0. 0.]
           [0. 0. 0.]
           ...
           [0. 0. 0.]
           [0. 0. 0.]
           [0. 0. 0.]]
        
          [[0. 0. 0.]
           [0. 0. 0.]
           [0. 0. 0.]
           ...
           [0. 0. 0.]
           [0. 0. 0.]
           [0. 0. 0.]]
        
          ...
        
          [[0. 0. 0.]
           [0. 0. 0.]
           [0. 0. 0.]
           ...
           [0. 0. 0.]
           [0. 0. 0.]
           [0. 0. 0.]]
        
          [[0. 0. 0.]
           [0. 0. 0.]
           [0. 0. 0.]
           ...
           [0. 0. 0.]
           [0. 0. 0.]
           [0. 0. 0.]]
        
          [[0. 0. 0.]
           [0. 0. 0.]
           [0. 0. 0.]
           ...
           [0. 0. 0.]
           [0. 0. 0.]
           [0. 0. 0.]]]], dtype=float32),
 jt.Var([[[[